server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - OPTIONS
            allow-credentials: true
        add-to-simple-url-handler-mapping: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/dislinkt"
  main:
    allow-bean-definition-overriding: true