server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: post-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: post-db
      port: 27017
      host: localhost
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/dislinkt"
  main:
    allow-bean-definition-overriding: true

logging:
  file:
    path: logs
