server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: profile-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: profile-db
      port: 27017
      host: localhost
      auto-index-creation: true