server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: profile-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: profile-db
      port: 27017
      host: localhost
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/dislinkt"
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 2MB

logging:
  file:
    path: logs

grpc:
  server:
    port: 9100
  client:
    connection-service:
      address: static://localhost:9099
      negotiationType: plaintext