server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
    prefer-ip-address: true
